#cloud-config
apt_sources:
  - source: "ppa:fenics-packages/fenics"

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - build-essential
  - fenics
  - python3-pip

